---
title: "R Notebook"
output: html_notebook
---

```{r}
scores <- function(ldata,pca,number)
{
  cdata <- ldata
  m <- dim(ldata)[2]
  for (i in 1:m)
    cdata[,i] <- ldata[,i] - pca$center[i]
  loads <- pca$rotation[,1:number]
  cdata <- as.matrix(cdata)
  f <- cdata %*% loads
  return (f)
}
```


```{r}
rates <- read.csv("./rates.csv",header = TRUE, row.names = 1 )
head(rates)
```

```{r}
maturities <- c(1/12,2/12,3/12,0.5,1,2,3,5,7,10,20,30)
round(maturities,3)
```

```{r}
pca <- prcomp(rates, scale = TRUE)
ss <- summary(pca)
summary(pca)
```

```{r}
Cumulative <- ss$importance[2,]
print(Cumulative)
sum(Cumulative[1:3])
```

```{r}
ldata <- rates
cdata <- ldata
m <- dim(ldata)[2]
for (i in 1:m)
  cdata[,i] <- ldata[,i] - ss$center[i]
loads <- ss$rotation[,1:number]
cdata <- as.matrix(cdata)
fscores <- cdata %*% loads
```


```{r}
number <- 3
matplot(fscores,type = 'l',lty = 1, col = 1:number,main = 'Factor Scores')
legend('topleft',c('shift','twist','butterfly'),col = 1:number,lty = 1)
abline(h=0)
```

```{r}
Loadings <- loads
Loadings
```

```{r}
restoreData<- function(fscores,loadings,center)
{
  npca <- dim(fscores)[2]
  myeigen <- t(loadings[,1:npca])
  rest <- fscores %*%myeigen
  m <- length(center)
  if (m == dim(rest)[2])
  {
    for (i in 1:m)
    rest[,i] <- rest[,i]+center[i]
  }
  return(rest)
}
rest <- restoreData(fscores, Loadings, ss$center)
head(rest)
```


```{r}
r
```

```{r}
restoreData<- function(fscores,loadings,center)
{
  npca <- dim(fscores)[2]
  myeigen <- t(loadings[,1:npca])
  rest <- fscores %*%myeigen
  m <- length(center)
  if (m == dim(rest)[2])
  {
    for (i in 1:m)
    rest[,i] <- rest[,i]+center[i]
  }
  return(rest)
}
restored_data_rates <- restoreData(fscores,Loadings,ss$center)
r <- unlist(rates[1,])
matplot(cbind(restored_data_rates[1,],r),type ='b',pch=21,lwd = 2,main = 'Restored rates',col = c('blue','green'),lty = 1)
legend('topleft',c('original rates','restored'),lty=1,lwd=2,col=c('blue','green') )
```

```{r}
var <- 25
```

```{r}
var
```

```{r}
rates[c("05/26/23", "05/30/23"), ]
```

```{r}
library(FinAna)
portfolio <- c(150,15,15,15,200,15,20,20,10,10,10,10) * 1000
par <- 1000
m <- 2
coupon <- 0.09
yield_1 <- rates["05/26/23", ]
yield_2 <- rates["05/30/23", ]
tau <- c(1/12,1/6,1/4,1/2,1,2,3,5,7,10,20,30 )
price1 <- sum(bond.price(portfolio,coupon,tau,yield_1,m))
price2 <- sum(bond.price(portfolio,coupon,tau,yield_2,m))
```

```{r}
price1
```


```{r}
portfolio_change <- price2-price1
portfolio_change
```


```{r}
fscores[nrow(fscores), ]
fscores_new <- rbind(fscores[nrow(fscores), ], c(0, 0, 0))
fscores_new[2, ] = c(3.515219,	1.464785 * 1.2,	0.480577)
fscores_new

```

```{r}
restored_data_rates_new <- restoreData(fscores_new,Loadings,ss$center)
head(restored_data_rates_new)
```

```{r}
library(FinAna)
portfolio <- c(150,15,15,15,200,15,20,20,10,10,10,10) * 1000
par <- 1000
m <- 2
coupon <- 0.09
yield_1 <- restored_data_rates_new[1, ]
yield_2 <- restored_data_rates_new[2, ]
tau <- c(1/12,1/6,1/4,1/2,1,2,3,5,7,10,20,30 )
price1 <- sum(bond.price(portfolio,coupon,tau,yield_1,m))
price2 <- sum(bond.price(portfolio,coupon,tau,yield_2,m))
forecast_change <- price2-price1
forecast_change
```

```{r}
result = list(
    var = var,
    Cumulative = Cumulative,
    Fscores = fscores,
    Loadings = Loadings,
    restored_data_rates= restored_data_rates,
    portfolio_change = portfolio_change,
    forecast_change= forecast_change
)
saveRDS(result,'./result.rds')
```

