---
title: "R Notebook"
output: html_notebook
---

```{r}
library(TSA)
```

```{r}
  data <- read.csv('var_25_Task_5.rds',header = T)
  head(data)
```

```{r}
x1 <- data[,1]
matplot(x1,type='p',main='Series1',pch=21)
```

```{r}
pgm<- periodogram(x1, col = "blue",lwd = 3,main = 'Series1. Periodogram',xlab='Frequency',ylab='Intensity',panel.first=grid(nx=NULL,ny = NULL))
```
0.18 и 0.355

```{r}
x2 <- data[,2]
matplot(x2,type='b',main='Series2',pch=21,col='purple')
```

```{r}
dx2 <-diff(x2)
matplot(dx2,type='b',main='Diff. Series2',pch=21,col='purple')
```

```{r}
pgm<- periodogram(dx2, col = "blue",lwd = 3,main = 'Diff. Series2. Periodogram',xlab='Frequency',ylab='Intensity',panel.first=grid(nx=NULL,ny = NULL))
```

```{r}
specc <-spec.pgram(dx2,c(7,7,7),col = "blue",lwd = 3,main = 'Diff. Series2. Smoothed Periodogram',xlab='Frequency',ylab='Intensity',panel.first=grid(nx=NULL,ny = NULL))
```

```{r}
l <- Re(fft(log(abs(fft(dx2))), inverse = TRUE))
l[1]=0
barplot(l[1:100],col = "blue",main="Kepstr",panel.first=grid(nx=NULL,ny = NULL))
```

```{r}
l[12]
```

```{r}
x3 <- data[,3]
matplot(x3,type='b',main='Series3',pch=20,col='blue')
```

```{r}
prgrm<- periodogram(x3, col = "blue",lwd = 3,plot = FALSE)
plot(prgrm$freq,prgrm$spec,main = "Series3. Periodogram", type = 'b',pch = 20, col='blue')
```

```{r}
sd(prgrm$spec)
```

```{r}
sm_prgrm <-spec.pgram(x3,c(7,7,7),plot=FALSE)
plot(sm_prgrm$freq,sm_prgrm$spec,type = 'b',pch = 20,main = "Series3. Smoothed Periodogram",col='blue')
```

```{r}
sd(sm_prgrm$spec)
```

